Add basic grid based movement
Online-Pluisje-Art/Operation-Blackwell pull request #12
Opened 2021-10-03 19:29 UTC by Dennisbonke

This PR adds a basic grid (square, 6x3), with a nice white tictac capsule that can move to any adjacent tile (including diagonals). Checking is applied to make sure that the requested move is valid. Move the tictac by left clicking on adjacent cells.

2021-10-04 08:38 UTC, Westlanderz commented on Assets/Scripts/Grid.cs
> +	// Graciously taken from the interwebs, draws a line like Debug.DrawLine does
End with a sentence with a `.`

2021-10-04 08:40 UTC, Westlanderz requested changes
Except for that one sentence that does not end with the `.` the PR looks good and ready to merge.

2021-10-05 08:48 UTC, Dennisbonke commented on Assets/Scripts/Grid.cs
> +	// Graciously taken from the interwebs, draws a line like Debug.DrawLine does
Solved.

2021-10-05 08:53 UTC, Westlanderz requested changes
Still missing some `.`, we missed them last review.

2021-10-05 08:55 UTC, Westlanderz approved these changes
LGTM

2021-10-05 08:55 UTC, merged