Boss fight
Online-Pluisje-Art/Operation-Blackwell pull request #143
Opened 2022-01-18 13:19 UTC by Westlanderz

This PR adds a boss fight. It only does not add sprites/animations to the boss and not all of the stages of that boss fight.

2022-01-18 14:20 UTC, Dennisbonke requested changes
Some small code style violations. Looks good otherwise.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +			for (int i = 0; i < barAmount; i++) {
Code style violation, no space between `for` and `(`.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +			for (int i = 0; i < barList_.Count; i++) {
Code style violation, no space between `for` and `(`.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +				if (fillValue_ <= barValueMin) {
Code style violation, no space between `if` and `(`.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +					if (fillValue_ >= barValueMax) {
Code style violation, no space between `if` and `(`.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +				if (fillAmount >= 1f) {
Code style violation, no space between `if` and `(`.

2022-01-18 14:20 UTC, Dennisbonke commented on Assets/Scripts/UI/GlobalHealthBar.cs
> +					if (barFilledImage.fillAmount < 1f) {
Code style violation, no space between `if` and `(`.

2022-01-18 14:36 UTC, drfdaniel submitted a review, later dismissed
LGTM

2022-01-19 10:10 UTC, Dennisbonke approved these changes
LGTM

2022-01-19 10:10 UTC, merged