Animation
Online-Pluisje-Art/Operation-Blackwell pull request #61
Opened 2021-11-10 14:30 UTC by LordMittens

Ik heb animaties toe gevoegd. player prefeb heeft nu een animator, er is een animation folder en Move Velocity is aangepast

2021-11-10 14:44 UTC, Dennisbonke commented
Please use proper commit messages conform the commit style (see [here](https://docs.opa.rip)) and we use English on GitHub, so please switch to English.

2021-11-10 14:48 UTC, Dennisbonke requested changes
Styling errors, please fix. Also, English is used here, so translate your PR message to English and write proper commit messages.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +		[SerializeField] Animator animator;
Missing modifier, lacking code style.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if (this.name == "Player")
No spaces between `if` and `(`.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if (this.name == "Player")
And no `{` and `}` either, please check the code style.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +		private void updateAnimation()
This entire function is scuffed, check the code style and reformat.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if ((velocityVector_.x == 0) && (velocityVector_.y == 0))
Doesn't match code style.

2021-11-10 14:48 UTC, Dennisbonke commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			else
Doesn't match code style.

2021-11-10 14:48 UTC, Westlanderz requested changes

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +		[SerializeField] Animator animator;
This misses the modifier `private` and a trailing underscore.

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if (this.name == "Player")
Please make name a variable that can be set.

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +        {
This is not correct with the code style.

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if (this.name == "Player")
Code style issues.

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			Debug.Log(velocityVector_);
Remove unnecessary `Debug.Logs`.

2021-11-10 14:48 UTC, Westlanderz commented on Assets/Scripts/Player/MoveVelocity/MoveVelocity.cs
> +			if ((velocityVector_.x == 0) && (velocityVector_.y == 0))
More code style issues.

2021-11-11 12:00 UTC, Westlanderz approved these changes

2021-11-11 12:08 UTC, Westlanderz submitted a review, later dismissed

2021-11-11 15:05 UTC, Dennisbonke approved these changes
LGTM now.

2021-11-11 15:06 UTC, Westlanderz approved these changes
LGTM

2021-11-11 15:06 UTC, merged