Add basic interactables through an interface
Online-Pluisje-Art/Operation-Blackwell pull request #68
Opened 2021-11-20 17:26 UTC by Westlanderz

This PR adds the ability to make interactables by creating a new script for that interactable and adding it to a prefab.

2021-11-21 19:58 UTC, drfdaniel submitted a review, later dismissed
LGTM, all is logical IMO, idk about classes and stuff though. But I trust your judgment

2021-11-21 20:03 UTC, Dennisbonke requested changes
Code looks good, 2 minor code style issues.

2021-11-21 20:03 UTC, Dennisbonke commented on Assets/Scripts/Core/Interactables/Crate.cs
> +}
Missing newline at the end of file.

2021-11-21 20:03 UTC, Dennisbonke commented on Assets/Scripts/Core/Interactables/IInteractable.cs
> +}
Missing newline at the end of file.

2021-11-22 11:50 UTC, Dennisbonke approved these changes
LGTM

2021-11-22 11:50 UTC, merged