Add camera movement
Online-Pluisje-Art/Operation-Blackwell pull request #8
Opened 2021-09-30 10:14 UTC by Westlanderz

This PR adds the movement system for the camera by making use of a camera controller and movement controller. With this you can control the camera through the scene with WASD.

2021-10-03 19:44 UTC, Dennisbonke requested changes
Code looks good, I assume you tested it of course. A few notes on the coding style tho.

- The script files seem to be space indented, we use tabs.
- Comments are full English sentences, they start with a capital and end with a `.`, please recheck them.
- All files (where applicable of course) shall have an empty line at the end of the file, which is lacking here too.

2021-10-03 19:44 UTC, Dennisbonke commented on Assets/Scripts/CameraController.cs
> +    // The movmentcontroller of the camera
A typo here, it should be movementcontroller, not movmentcontroller.

2021-10-03 19:44 UTC, Dennisbonke commented on Assets/Scripts/CameraMovement.cs
> +        if (Input.GetKey(KeyCode.W)) {
This doesn't follow the coding style, `if` statements do not get a space before the opening `(`.

2021-10-04 08:29 UTC, Westlanderz commented
@Dennisbonke please check the new commit for the mistakes that should have been fixed now

2021-10-05 08:39 UTC, Dennisbonke approved these changes
LGTM

2021-10-05 08:39 UTC, merged